before_install:
- sudo apt-get -qq update
- sudo apt-get install -y libjson0 libjson0-dev

language: C
script: gcc main.c analysis.c functions.c init_config.c requests.c response.c $(pkg-config --libs --cflags libcurl) -l json -std=gnu11

